<?php

/**
* Implements hook_menu().
*/
function homer_menu() {
  $items = array();

  $items['homer'] = array(
    'page callback' => 'homer_html',
    'access callback' => TRUE, // public access!
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function homer_block_info() {
  $blocks['hpublicidad'] = array(
    'info' => t('Chart Viaje'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['hpublicidad1'] = array(
    'info' => t('Chart Asesores'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['hpublicidad2'] = array(
    'info' => t('Chart Publicidad comparativo'),
    'cache' => DRUPAL_NO_CACHE,
  );
 return $blocks;
}

function homer_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'hpublicidad':
      $block['subject'] = t('Gastos de viaje 2007 - 2014');
      $block['content'] = homer_row();
      break;
    case 'hpublicidad1':
      $block['subject'] = t('Gastos por asesorías y consultorías 2007 - 2014');
      $block['content'] = homer_row1();
      break;
    case 'hpublicidad2':
      $block['subject'] = t('Gastos por proveedores');
      $block['content'] = homer_row2();
      break;
  }
  return $block;
}

//Controlador
//

function homer_chart1($arr, $title){

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#title' => t($title),
  );

  $chart['gasto'] = array(
    '#type' => 'chart_data',
    '#title' => t('Año'),
    '#data' => $arr,
    '#suffix' => ' Soles',
  );
  $chart['xaxis'] = array(
    '#type' => 'chart_xaxis',
    '#labels' => array('2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014'),
  );

  $example['chart'] = $chart;

  return $example;
}

function homer_chart2($arr1, $arr2, $title){

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#renderto' => 'container',
    '#title' => t($title),
  );

  $chart['gasto1'] = array(
    '#type' => 'chart_data',
    '#title' => t('Castañeda'),
    '#data' => $arr1,
    '#suffix' => ' Soles',
    '#color' => '#ffff00',
  );

  $chart['gasto2'] = array(
    '#type' => 'chart_data',
    '#title' => t('Villarán'),
    '#data' => $arr2,
    '#suffix' => ' Soles',
    '#color' => '#00cc00',
  );
  $chart['xaxis'] = array(
    '#type' => 'chart_xaxis',
    '#labels' => array('1', '2', '3', '4'),
  );

  $example['chart'] = $chart;

  return $example;
}

function homer_row(){

  $html = '';

  $c1 = homer_chart1(
    array(0, 0, 15641, 18782, 10189, 69466, 20827, 8493),
    'Gastos de viaje por años sucesivos'
  );
  $c2 = homer_chart2(
    array(0, 0, 15641, 18782),
    array(10189, 69466, 20827, 8493),
    'Gastos de viajes año de gestión Castañeda vs Villarán'
  );

  $html.= '<div class="row">';

  $html.= '<div class="col-md-6">';
  $html.= drupal_render($c1);
  $html.= '</div>';
  $html.= '<div class="col-md-6">';
  $html.= drupal_render($c2);
  $html.= '</div>';

  $html.= '</div>';

 return $html;
}

function homer_row1(){
  $c3 = homer_chart1(
  array(74651, 312144, 63880, 39650, 12655, 23334, 65923, 58882),
    'Gastos de consultoria y asesorias por años sucesivos'
  );

  $c4 = homer_chart2(
    array(74651, 312144, 63880, 39650),
    array(12655, 23334, 65923, 58882),
    'Gastos de consultoria y asesorias año de gestión Castañeda vs Villarán'
  );

  $html = '<div class="row">';

  $html.= '<div class="col-md-6">';
  $html.= drupal_render($c3);
  $html.= '</div>';
  $html.= '<div class="col-md-6">';
  $html.= drupal_render($c4);
  $html.= '</div>';

  $html.= '</div>';

  return $html;
}

function homer_row2(){
  $c5 = homer_chart1(
  array(0, 0, 0, 0, 688010, 1385214, 597580, 229052),
    'Gastos de proveedores por años sucesivos'
  );

  $c6 = homer_chart2(
    array(0,0,0,0),
    array(688010, 1385214, 597580, 229052),
    'Gastos de proveedores por año de gestión Castañeda vs Villarán'
  );

  $html = '<div class="row">';

  $html.= '<div class="col-md-12">';
  $html.= drupal_render($c5);
  //$html.= drupal_render($c6);
  $html.= '</div>';

  $html.= '</div>';

  return $html;
}


function homer_chartprov($arr, $prv, $title=''){

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#title' => t($title),
  );


for ($i=0; $i < count($arr); $i++) {
  $chart['g'.$i] = array(
    '#type' => 'chart_data',
    '#title' => t($prv[$i]),
    '#data' => array($arr[$i]),
    '#suffix' => 'N. Soles',
  );
}


  $chart['xaxis'] = array(
    '#type' => 'chart_xaxis',
    '#labels' => array('año 2007'),
  );

  $example['chart'] = $chart;

  return $example;
}

function homer_prov(){
  $html = '';
  $nn = 2007;
  $arr = array();
  $prv = array();

  for ($n=0; $n < 4; $n++) {
    $html.= '<hr/>';

    for ($i=0; $i < 20; $i++) {
      $arr[$i] = rand(1, 10);
      $prv[$i] = 'Proveedor '.$i;
    }

    $title = 'Gastos por proveedor en el año '.$nn;
    $chart = homer_chartprov($arr, $prv, $title);
    $html.= drupal_render($chart);

    $nn++;
  }

  return $html;
}

function homer_html(){
  $html = 'test!';
  return $html;
}
