<?php

/**
* Implements hook_menu().
*/
function homer_menu() {
  $items = array();

  $items['homer'] = array(
    'page callback' => 'homer_html',
    'access callback' => TRUE, // public access!
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function homer_block_info() {
  $blocks['hpublicidad'] = array(
    'info' => t('Chart Publicidad por años'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['hpublicidad2'] = array(
    'info' => t('Chart Publicidad comparativo'),
    'cache' => DRUPAL_NO_CACHE,
  );
 return $blocks;
}

function homer_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'hpublicidad':
      $block['subject'] = t('Totales de gasto en publicidad por años');
      $block['content'] = homer_row();
      break;
    case 'hpublicidad2':
      $block['subject'] = t('Totales de gasto en publicidad por año de gobierno');
      $block['content'] = homer_chart2();
      break;
  }
  return $block;
}

//Controlador
//

function homer_chart1(){

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#title' => t(''),
  );

  $chart['gasto'] = array(
    '#type' => 'chart_data',
    '#title' => t('Año'),
    '#data' => array(10, 20, 30, 16, 80, 20, 12, 60),
    '#suffix' => 'Ns',
  );
  $chart['xaxis'] = array(
    '#type' => 'chart_xaxis',
    '#labels' => array('2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014'),
  );

  $example['chart'] = $chart;

  return $example;
}

function homer_chart2(){

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'column',
    '#renderto' => 'container',
    '#title' => t(''),
  );

  $chart['gasto1'] = array(
    '#type' => 'chart_data',
    '#title' => t('Castañeda'),
    '#data' => array(80, 20, 12, 60),
    '#suffix' => 'Ns',
  );

  $chart['gasto2'] = array(
    '#type' => 'chart_data',
    '#title' => t('Villarán'),
    '#data' => array(10, 20, 30, 16),
    '#suffix' => 'Ns',
  );
  $chart['xaxis'] = array(
    '#type' => 'chart_xaxis',
    '#labels' => array('1', '2', '3', '4'),
  );

  $example['chart'] = $chart;

  return $example;
}

function homer_row(){

  $c1 = homer_chart1();
  $c2 = homer_chart2();

  $html = '<div class="row">';
  $html.= '<div class="col-md-6">';
  $html.= drupal_render($c1);
  $html.= '</div>';
  $html.= '<div class="col-md-6">';
  $html.= drupal_render($c2);
  $html.= '</div>';
  $html.= '</div>';

 return $html;
}

function homer_html(){
  $html = 'test!';
  return $html;
}
